
name: Build-and-release-deploy-Dev

on:
  workflow_dispatch:

jobs:
  build-release-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist

      - name: change to dist
        run: cd dist

      - name: create file
        run: touch test.txt

      - name: List files in dist directory
        run: ls -l dist

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: "dist/"
          TARGET: "/home/ubuntu"
          SCRIPT_AFTER: |
            touch test2.txt
